food_site/food_site/urls.py
from sku_manage.admin import admin_site
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin_site.urls),
    path('', include('home.urls')),
    path('importer/', include('importer.urls')),
    path('reporting/', include('dep_report.urls')),
    path('reporting/', include('sales.urls')),
    path('search/', include('sku_manage.urls')),
    path('manufacturing/', include('manufacturing_goals.urls')),
    path('mfglinemap/', include('mfg_map.urls')),
]

food_site/home/urls.py
# home/urls.py
from django.conf.urls import url
from home import views
from django.urls import path


urlpatterns = [
    path('', views.index, name='index'),
    path('authin/', views.authin, name='authin'),
    path('authout/', views.authout, name='authout'),
    path('invalidlogin/', views.invalidlogin, name='invalidlogin'),
    path('help/', views.help, name='help'),
    path('aboutus/', views.aboutus, name='aboutus'),
    path('netlog/', views.netlog, name='netlog'),
    path('netret/', views.netret, name='netret'),
    path('authmid/', views.authmid, name='authmid'),
    path('user/', views.selectuser, name='selectuser'),
    path('user/<int:pk>/', views.edituser, name='edituser'),
    path('assistant/', views.assistant, name='assistant'),
    path('cya/', views.cya, name='cya'),
    path('cyaend/', views.cya_end, name='cyaend'),
    path('privacy-policy/', views.privacy, name='privacy-policy'),
]

food_site/sku_manage/urls.py
# sku_manage/urls.py
from django.conf.urls import url
from sku_manage import views
from django.urls import path

urlpatterns = [
	path('', views.search, name='search'),
	path('ingredient/', views.IngredientView, name='Ingredient'),
	path('productline/', views.ProductLineView, name='ProductLine'),
	path('sku/', views.SKUView, name='SKU'),
	path('formula/', views.FormulaView, name='formula'),
	path('manufacturingline/', views.ManufacturingLineView, name='ManufacturingLine'),
	path('ingredient/<int:pk>/', views.IngredientDetailView.as_view(), name='ingredient_detail'),
	path('productline/<int:pk>/', views.ProductLineDetailView.as_view(), name='product_line_detail'),
	path('sku/<int:pk>/', views.SKUDetailView.as_view(), name='sku_detail'),
	path('formula/<int:pk>/', views.FormulaDetailView.as_view(), name='formula_detail'),
	path('manufacturingline/<int:pk>/', views.ManufacturingLineDetailView.as_view(), name='mfg_line_detail'),
]

food_site/sku_manage/models.py
import re

from django.db import models
from django.core.exceptions import ValidationError

weights = ('Ounce', 'oz.', 'Pound', 'lb.', 'Ton', 'ton.', 'Gram', 'g.', 'Kilogram', 'kg.')
volumes = ('Fluid Ounce', 'fl.oz.', 'Pint', 'pt.', 'Quart', 'qt.', 'Gallon', 'gal.', 'Milliliter', 'mL', 'Liter', 'L')
counts = ('Count', 'count',)

def validate_upc(value):
    if len(value) != 12:
        raise ValidationError('UPC must be 12 digits long')
    pattern = re.compile('[0-9]{12}')
    if pattern.match(value) is None:
        raise ValidationError('UPC must only contain numbers')
    if 1 < int(value[0]) < 6:
        raise ValidationError('UPC first digit is not valid')
    sum_val = 0
    for i in range(0, 6):
        sum_val += int(value[i * 2])
    sum_val = sum_val * 3
    for i in range(0, 6):
        sum_val += int(value[i * 2 + 1])
    if sum_val % 10 != 0:
        raise ValidationError('UPC check digit is not valid')


def validate_gt_zero(value):
    if value <= 0:
        raise ValidationError('Must be greater than zero')


def gen_ingr_num():
    ingredients = Ingredient.objects.order_by('number')
    if len(ingredients) > 0 and ingredients[len(ingredients) - 1].number > len(ingredients) - 1:
        for i in range(0, len(ingredients)):
            if (ingredients[i].number > i):
                return i
    return len(ingredients)


def gen_sku_num():
    skus = SKU.objects.order_by('sku_num')
    if len(skus) > 0 and skus[len(skus) - 1].sku_num > len(skus) - 1:
        for i in range(0, len(skus)):
            if (skus[i].sku_num > i):
                return i
    return len(skus)


def gen_fla_num():
    formulas = Formula.objects.order_by('number')
    if len(formulas) > 0 and formulas[len(formulas) - 1].number > len(formulas) - 1:
        for i in range(0, len(formulas)):
            if (formulas[i].number > i):
                return i
    return len(formulas)


class Ingredient(models.Model):
    name = models.CharField(max_length=256, unique=True, verbose_name='Ingredient Name')
    number = models.PositiveIntegerField(unique=True, default=gen_ingr_num, verbose_name='Ingredient#')
    vendor_info = models.TextField(blank=True, verbose_name='Vendor Information')
    package_size = models.FloatField(validators=[validate_gt_zero])
    package_size_units = models.CharField(max_length=16,
                                          choices=[('Ounce', 'oz.'), ('Pound', 'lb.'), ('Ton', 'ton.'), ('Gram', 'g.'),
                                                   ('Kilogram', 'kg.'), ('Fluid Ounce', 'fl.oz.'), ('Pint', 'pt.'),
                                                   ('Quart', 'qt.'), ('Gallon', 'gal.'), ('Milliliter', 'mL'),
                                                   ('Liter', 'L'), ('Count', 'count')])
    cost = models.DecimalField(max_digits=12, decimal_places=2, validators=[validate_gt_zero])
    comment = models.TextField(blank=True)

    class Meta:
        permissions = (('report_ingredient', 'Can view ingredient dependency report'),)

    def __str__(self):
        return self.name

    def get_serializable_string_array(self):
        return [str(self.number), self.name, self.vendor_info, str(self.package_size), self.package_size_units,
                str(self.cost), self.comment]


class ProductLine(models.Model):
    name = models.CharField(max_length=256, unique=True)

    def __str__(self):
        return self.name


class Formula(models.Model):
    name = models.CharField(max_length=32)
    number = models.IntegerField(unique=True, default=gen_fla_num, verbose_name='Formula#')
    comment = models.TextField(blank=True)

    def __str__(self):
        return self.name

    def get_serializable_string_array(self):
        return [str(self.number), self.name, str(self.comment)]


class SKU(models.Model):
    name = models.CharField(max_length=32)
    sku_num = models.IntegerField(unique=True, default=gen_sku_num, verbose_name='SKU#')
    case_upc = models.CharField(max_length=12, unique=True, validators=[validate_upc], verbose_name='Case UPC')
    unit_upc = models.CharField(max_length=12, validators=[validate_upc], verbose_name='Unit UPC')
    unit_size = models.CharField(max_length=256)
    units_per_case = models.PositiveIntegerField(validators=[validate_gt_zero])
    product_line = models.ForeignKey(ProductLine, on_delete=models.PROTECT)
    formula = models.ForeignKey(Formula, on_delete=models.PROTECT)
    formula_scale = models.FloatField(default=1.0, validators=[validate_gt_zero], verbose_name='Formula Scale Factor')
    mfg_rate = models.FloatField(validators=[validate_gt_zero], verbose_name='Manufacturing Rate')
    mfg_setup_cost = models.DecimalField(max_digits=12, decimal_places=2, validators=[validate_gt_zero], verbose_name='Manufacturing Setup Cost')
    mfg_run_cost = models.DecimalField(max_digits=12, decimal_places=2, validators=[validate_gt_zero], verbose_name='Manufacturing Run Cost per Case')
    comment = models.TextField(blank=True)

    def __str__(self):
        return "{name}: {unit_size} * {units_per_case} (SKU#{sku_num})".format(name=self.name, unit_size=self.unit_size, units_per_case=self.units_per_case, sku_num=self.sku_num)

    def get_serializable_string_array(self):
        return [str(self.sku_num), self.name, self.case_upc, self.unit_upc, self.unit_size, str(self.units_per_case),
                self.product_line.name, str(self.formula.number), str(self.formula_scale), str(self.mfg_rate),
                str(self.mfg_setup_cost), str(self.mfg_run_cost), self.comment]

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        from sales import tasks
        tasks.scrape_sku(self.sku_num)

class ManufacturingLine(models.Model):
    name = models.CharField(max_length=32)
    shortname = models.CharField(max_length=5, unique=True)
    comment = models.TextField(blank=True)

    class Meta:
        permissions = (('report_manufacturingline', 'Can view manufacturing schedule reports'),)

    def __str__(self):
        return "{name} ({shortname})".format(name=self.name, shortname=self.shortname)


class IngredientQty(models.Model):
    formula = models.ForeignKey(Formula, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.PROTECT)
    quantity = models.FloatField(validators=[validate_gt_zero])
    quantity_units = models.CharField(max_length=16,
                                      choices=[('Ounce', 'oz.'), ('Pound', 'lb.'), ('Ton', 'ton.'), ('Gram', 'g.'),
                                                 ('Kilogram', 'kg.'), ('Fluid Ounce', 'fl.oz.'), ('Pint', 'pt.'),
                                                 ('Quart', 'qt.'), ('Gallon', 'gal.'), ('Milliliter', 'mL'),
                                                 ('Liter', 'L'), ('Count', 'count')])

    class Meta:
        unique_together = ("formula", "ingredient")

    def clean(self):
        if self.quantity_units in weights and self.ingredient.package_size_units not in weights:
            raise ValidationError("Quantity measured in weight but ingredient package size is not")
        if self.quantity_units in volumes and self.ingredient.package_size_units not in volumes:
            raise ValidationError("Quantity measured in volume but ingredient package size is not")
        if self.quantity_units in counts and self.ingredient.package_size_units not in counts:
            raise ValidationError("Quantity measured in raw count but ingredient package size is not")

    def get_serializable_string_array(self):
        return [str(self.formula.number), str(self.ingredient.number), str(self.quantity), str(self.quantity_units)]


class SkuMfgLine(models.Model):
    sku = models.ForeignKey(SKU, on_delete=models.CASCADE)
    mfg_line = models.ForeignKey(ManufacturingLine, on_delete=models.PROTECT)

    class Meta:
        unique_together = ("sku", "mfg_line")

food_site/sku_manage/templates/sku_manage/base.html
<!-- sku_manage/templates/ingredient.html -->
<!DOCTYPE html>
<html>
	{% load staticfiles %}
	{% load static %}
	<head>
		<meta charset="utf-8">
        	<title>HypoMeals</title>
        	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        	<link rel="stylesheet" type="text/css" href="{% static "sku_manage/style.css" %}" />
        	{% block styling %}
        	{% endblock styling %}
	</head>
	<body>
		{% include "sku_manage/header.html" %}
		{% block content %}
		{% endblock content %}
	</body>
</html>

food_site/sku_manage/templates/sku_manage/data.html
{% extends "base.html" %}
{% block content %}
    <div class="inline">
        <h1>{{ title }}</h1>
        {% if perms.sku_manage.add_sku %}
            <a class="btn" href="/admin/sku_manage/{{ type }}/add/">Add&nbsp<i class="fa fa-plus"></i></a>
        {% endif %}
    </div>
	{% include "data/filters.html" %}
	<br>
	{% if table.rows %}
		<form class="form-inline" method="post">
			{% csrf_token %}
			<button type="submit" name="export_data">Download - {{ table.rows|length }} result(s)</button>
		</form>
	{% endif %}
	<div class="table", style="overflow-x:auto;">
		{% load render_table from django_tables2 %}
		{% load bootstrap3 %}
		{% render_table table %}
	</div>
	{% if queryset.all|length > 25 %}
		<form class="form-inline" method="get">
			{% if paginated %}
				<button type="submit" name="remove_pagination">View All Records</button>
			{% else %}
				<button type="submit" name="add_pagination"">Paged View</button>
			{% endif %}
		</form>
	{% endif %}
{% endblock content %}

food_site/sku_manage/templates/sku_manage/formula_detail.html
{% extends "base.html" %}
{% block content %}
    <div class="inline">
        <h1>{{ formula }}</h1>
        {% if perms.sku_manage.change_formula %}
            <a class="btn" href="{% url 'admin:sku_manage_formula_change' formula.pk %}"><i class="fa fa-pencil"></i></a>
        {% endif %}
        {% if perms.sku_manage.delete_formula %}
            <a class="btn" href="{% url 'admin:sku_manage_formula_delete' formula.pk %}"><i class="fa fa-trash"></i></a>
        {% endif %}
    </div>
    <p>General Information:</p>
    <ul>
    	<li>Name: {{ formula.name }}</li>
    	<li>Formula#: {{ formula.number }}</li>
    	<li>Comment: {{ formula.comment }}</li>
    </ul>
    <p>{{ formula.ingredientqty_set.all|length }} Ingredients:</p>
    <ul>
    	{% for choice in formula.ingredientqty_set.all %}
        	<li> <a class="detail_list" href="{% url 'ingredient_detail' choice.ingredient.pk %}">{{ choice.ingredient.name }}</a> - {{ choice.quantity }} {{ choice.quantity_units }}</li>
    	{% endfor %}
    </ul>
    <p>{{ formula.sku_set.all|length }} SKUs:</p>
    <ul>
    	{% for sku in formula.sku_set.all %}
        	<li> <a class="detail_list" href="{% url 'sku_detail' sku.pk %}">{{ sku }}</a> - Scale {{ sku.formula_scale }}</li>
    	{% endfor %}
    </ul>
{% endblock content %}

food_site/sku_manage/templates/sku_manage/ingredient.html
<!-- sku_manage/templates/ingredient.html -->
<!DOCTYPE html>
<html>
	{% load staticfiles %}
	{% load static %}
	{% load render_table from django_tables2 %}
	{% load bootstrap3 %}
	<head>
		<meta charset="utf-8">
        	<title>HypoMeals</title>
        	<link rel="stylesheet" type="text/css" href="{% static "sku_manage/data.css" %}" />
	</head>
	<body>
		<h1>Data shown below:</h1>
		<div style="overflow-x:auto;">
		{% if filter %}
			<form action="" method-"get" class="form form-inline">
				{% bootstrap_form filter.form layout='inline' %}
				{% bootstrap_button 'filter' %}
			</form>
		{% endif %}
		{% render_table table %}
		</div>
	</body>
<html>

food_site/sku_manage/templates/sku_manage/ingredient_detail.html
{% extends "base.html" %}
{% block content %}
	<div class="inline">
		<h1>{{ ingredient }}</h1>
		{% if perms.sku_manage.change_ingredient %}
			<a class="btn" href="{% url 'admin:sku_manage_ingredient_change' ingredient.pk %}"><i class="fa fa-pencil"></i></a>
		{% endif %}
		{% if perms.sku_manage.delete_ingredient %}
			<a class="btn" href="{% url 'admin:sku_manage_ingredient_delete' ingredient.pk %}"><i class="fa fa-trash"></i></a>
		{% endif %}
	</div>
	<p>General Information:</p>
	<ul>
		<li>Ingredient Name: {{ ingredient.name }}</li>
		<li>Ingredient#: {{ ingredient.number }}</li>
		<li>Package Size: {{ ingredient.package_size }} {{ ingredient.package_size_units }}</li>
		<li>Package Cost: ${{ ingredient.cost }} (USD)</li>
		<li>Vendor Information: {{ ingredient.vendor_info }}</li>
		<li>Comment: {{ ingredient.comment }}</li>
	</ul>
	<p>{{ ingredient.ingredientqty_set.all|length }} Formulas:</p>
	<ul>
		{% for choice in ingredient.ingredientqty_set.all %}
			<li><a class="detail_list" href="{% url 'formula_detail' choice.formula.pk %}"> {{ choice.formula }}</a> - {{ choice.quantity }} {{ choice.quantity_units }}</li>
		{% endfor %}
	</ul>
	<p>SKUs:</p>
	<ul>
		{% for ingq in ingredient.ingredientqty_set.all %}
			{% for sku in ingq.formula.sku_set.all %}
				<li><a class="detail_list" href="{% url 'sku_detail' sku.pk %}"> {{ sku }}</a></li>
			{% endfor %}
		{% endfor %}
	</ul>
{% endblock content %}

food_site/sku_manage/templates/sku_manage/mfg_line_detail.html
{% extends "base.html" %}
{% block content %}
    <div class="inline">
        <h1>{{ manufacturingline }}</h1>
        {% if perms.sku_manage.change_manufacturingline %}
            <a class="btn" href="{% url 'admin:sku_manage_manufacturingline_change' manufacturingline.pk %}"><i class="fa fa-pencil"></i></a>
        {% endif %}
        {% if perms.sku_manage.delete_manufacturingline %}
            <a class="btn" href="{% url 'admin:sku_manage_manufacturingline_delete' manufacturingline.pk %}"><i class="fa fa-trash"></i></a>
        {% endif %}
    </div>
    <p>General Information:</p>
    <ul>
        <li>Name: {{ manufacturingline.name }}</li>
        <li>Shortname: {{ manufacturingline.shortname }}</li>
    </ul>
    <p>{{ manufacturingline.skumfgline_set.all|length }} SKUs:</p>
    <ul>
    	{% for choice in manufacturingline.skumfgline_set.all %}
        	<li><a class="detail_list" href="{% url 'sku_detail' choice.sku.pk %}"> {{ choice.sku }}</a></li>
    	{% endfor %}
    </ul>
{% endblock content %}

food_site/sku_manage/templates/sku_manage/product_line_detail.html
{% extends "base.html" %}
{% block content %}
    <div class="inline">
        <h1>{{ productline }}</h1>
        {% if perms.sku_manage.change_productline %}
            <a class="btn" href="{% url 'admin:sku_manage_productline_change' productline.pk %}"><i class="fa fa-pencil"></i></a>
        {% endif %}
        {% if perms.sku_manage.delete_productline %}
            <a class="btn" href="{% url 'admin:sku_manage_productline_delete' productline.pk %}"><i class="fa fa-trash"></i></a>
        {% endif %}
    </div>
    <p>General Information:</p>
    <ul>
    	<li>Product Line Name: {{ productline.name }}</li>
    </ul>
    <p>{{ productline.sku_set.all|length }} SKUs:</p>
    <ul>
    	{% for sku in productline.sku_set.all %}
        	<li><a class="detail_list" href="{% url 'sku_detail' sku.pk %}"> {{ sku }}</a></li>
    	{% endfor %}
    </ul>
{% endblock content %}

food_site/sku_manage/templates/sku_manage/search.html
{% extends "base.html" %}
{% block content %}
	<div class="menu-buttons">
		<h1>What do you wish to search for?</h1>
		<a href="{% url 'Ingredient' %}">Ingredients</a> 
		<a href="{% url 'ProductLine' %}">Products</a>
		<a href="{% url 'SKU' %}">SKUs</a>
		<a href="{% url 'formula' %}">Formulas</a>
		<a href="{% url 'ManufacturingLine' %}">Manufacturing Lines</a>
	</div>
{% endblock content %}

food_site/sku_manage/templates/sku_manage/sku_detail.html
{% extends "base.html" %}
{% block content %}
	<div class="inline">
		<h1>{{ sku }}</h1>
		{% if perms.sku_manage.change_sku %}
			<a class="btn" href="{% url 'admin:sku_manage_sku_change' sku.pk %}"><i class="fa fa-pencil"></i></a>
		{% endif %}
		{% if perms.sku_manage.delete_sku %}
			<a class="btn" href="{% url 'admin:sku_manage_sku_delete' sku.pk %}"><i class="fa fa-trash"></i></a>
		{% endif %}
	</div>
	<p>General Information:</p>
	<ul>
		<li>Name: {{ sku.name }}</li>
		<li>SKU#: {{ sku.sku_num }}</li>
		<li>Case UPC: {{ sku.case_upc }}</li>
		<li>Unit UPC: {{ sku.unit_upc }}</li>
		<li>Unit Size: {{ sku.unit_size }}</li>
		<li>Units Per Case: {{ sku.units_per_case }}</li>
		<li>Product Line: <a class="detail_list" href="{% url 'product_line_detail' sku.product_line.pk %}">{{ sku.product_line }}</a></li>
		<li>Formula: <a class="detail_list" href="{% url 'formula_detail' sku.formula.pk %}">{{ sku.formula }}</a></li>
		<li>Formula Scale: {{ sku.formula_scale }}</li>
		<li>Manufacturing Rate: {{ sku.mfg_rate }}</li>
		<li>Manufacturing Setup Cost: ${{ sku.mfg_setup_cost }} (USD)</li>
		<li>Manufacturing Run Cost: ${{ sku.mfg_run_cost }} per case (USD)</li>
		<li>Comment: {{ sku.comment }}</li>
	</ul>
	<a class="detail_list" href="{% url 'sku_drilldown' sku.pk %}">SKU Sales Report</a>
	<p>{{ sku.skumfgline_set.all|length }} Manufacturing Lines:</p>
	<ul>
		{% for choice in sku.skumfgline_set.all %}
	    	<li> <a class="detail_list" href="{% url 'mfg_line_detail' choice.mfg_line.pk %}">{{ choice.mfg_line }}</a></li>
		{% endfor %}
	</ul>
	<p>Formula - {{ sku.formula.ingredientqty_set.all|length }} Ingredients:</p>
	<ul>
		{% for choice in sku.formula.ingredientqty_set.all %}
	    	<li> <a class="detail_list" href="{% url 'ingredient_detail' choice.ingredient.pk %}">{{ choice.ingredient.name }}</a> - {{ choice.quantity }} {{ choice.quantity_units }}</li>
		{% endfor %}
	</ul>
{% endblock content %}