food_site/food_site/urls.py
from sku_manage.admin import admin_site
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin_site.urls),
    path('', include('home.urls')),
    path('importer/', include('importer.urls')),
    path('reporting/', include('dep_report.urls')),
    path('reporting/', include('sales.urls')),
    path('search/', include('sku_manage.urls')),
    path('manufacturing/', include('manufacturing_goals.urls')),
    path('mfglinemap/', include('mfg_map.urls')),
]

food_site/home/urls.py
# home/urls.py
from django.conf.urls import url
from home import views
from django.urls import path


urlpatterns = [
    path('', views.index, name='index'),
    path('authin/', views.authin, name='authin'),
    path('authout/', views.authout, name='authout'),
    path('invalidlogin/', views.invalidlogin, name='invalidlogin'),
    path('help/', views.help, name='help'),
    path('aboutus/', views.aboutus, name='aboutus'),
    path('netlog/', views.netlog, name='netlog'),
    path('netret/', views.netret, name='netret'),
    path('authmid/', views.authmid, name='authmid'),
    path('user/', views.selectuser, name='selectuser'),
    path('user/<int:pk>/', views.edituser, name='edituser'),
    path('assistant/', views.assistant, name='assistant'),
    path('cya/', views.cya, name='cya'),
    path('cyaend/', views.cya_end, name='cyaend'),
    path('privacy-policy/', views.privacy, name='privacy-policy'),
]

food_site/manufacturing_goals/urls.py
from django.conf.urls import url
from manufacturing_goals import views
from django.urls import path

urlpatterns = [
	path('', views.manufacturing, name='manufacturing'),
	path('timeline/edit/', views.timeline, name='timeline'),
	path('timeline/', views.timeline_viewer, name='timeline_viewer'),
	path('manufqty/', views.manufqty, name='manufqty'),
	path('manufdetails/', views.manufdetails, name='manufdetails'),
	path('add/<int:pk>/', views.goal_add, name='mfg_goal_add'),
	path('remove/<int:pk>/', views.goal_remove, name='mfg_goal_remove'),
	path('enable/', views.enable_menu, name='enable_menu'),
	path('projection/<int:pk>/', views.project, name='projection'),
	path('projection/', views.stupid, name='stupid'),
	path('dateset/', views.set_project_date, name='dateset'),
	path('enable/<int:pk>/', views.enable_goal, name='enable_goal'),
	path('timeline/edit/autoschedule/', views.auto_schedule_select, name='auto_schedule_select'),
	path('timeline/edit/autoschedule/add/<int:pk>/', views.auto_schedule_add, name='autoschedule_add'),
	path('timeline/edit/autoschedule/remove/<int:pk>/', views.auto_schedule_remove, name='autoschedule_remove'),
	path('timeline/edit/autoschedule/run/', views.auto_schedule, name='auto_schedule'),
]

food_site/manufacturing_goals/models.py
from datetime import datetime, time, timedelta
import time as sys_time

from django.utils import timezone
from django.db import models
from django.core.exceptions import ValidationError
from sku_manage.models import Ingredient, ProductLine, SKU, ManufacturingLine, IngredientQty, SkuMfgLine
from django.contrib.auth.models import User

def validate_workday(value):
	if value.hour < 8 or value.hour > 18:
		raise ValidationError('Manufacturing start time outside of workday')

class ManufacturingGoal(models.Model):
	name = models.CharField(max_length=500)
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	last_edit = models.DateTimeField(default=timezone.now, verbose_name='Last Edit Timestamp')
	deadline = models.DateField()
	enabled = models.BooleanField(default=False)

	class Meta:
		permissions = (('enable_manufacturinggoal', 'Can enable/disable manufacturing goals'),)
	
	def save(self, *args, **kwargs):
		self.last_edit = timezone.now()
		super().save(*args, **kwargs)

	def __str__(self):
		return self.name

class ManufacturingQty(models.Model):
	sku = models.ForeignKey(SKU, on_delete=models.CASCADE, verbose_name='SKU')
	caseqty = models.FloatField(verbose_name='Case Quantity')
	goal = models.ForeignKey(ManufacturingGoal, on_delete=models.CASCADE)

class ScheduleItem(models.Model):
	mfgqty = models.OneToOneField(ManufacturingQty, on_delete=models.CASCADE)
	mfgline = models.ForeignKey(ManufacturingLine, on_delete=models.CASCADE)
	start = models.DateTimeField(validators=[validate_workday])
	endoverride = models.DateTimeField(validators=[validate_workday], blank=True, null=True)
	provisional_user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)

	def clean(self):
		if SkuMfgLine.objects.filter(sku=self.mfgqty.sku, mfg_line=self.mfgline).count() == 0:
			raise ValidationError('Cannot produce selected SKU on manufacturing line')

	def duration(self):
		if (self.mfgqty.caseqty/self.mfgqty.sku.mfg_rate) < 1:
			return timedelta(hours=1)
		return timedelta(hours=(self.mfgqty.caseqty/self.mfgqty.sku.mfg_rate))

	def end_calc(self):
		endtime = self.start + self.duration()
		index = self.start.replace(hour=18, tzinfo=timezone.get_current_timezone())
		while index < endtime:
			endtime += timedelta(hours=14)
			index += timedelta(days=1)
		return endtime

	def end(self):
		if self.endoverride is not None:
			return self.endoverride
		return self.end_calc()

	def too_late(self):
		return datetime.combine(self.mfgqty.goal.deadline, time.max).replace(tzinfo=timezone.get_current_timezone()) < self.end()

	def start_time(self):
		return self.start.strftime("%Y-%m-%dT%H:%M:%S%z")

	def end_time(self):
		return self.end().strftime("%Y-%m-%dT%H:%M:%S%z")

	def __str__(self):
		return str(self.mfgqty.goal.name) + ': ' + self.mfgqty.sku.name + ', due by ' + '{:%Y-%m-%d}'.format(self.mfgqty.goal.deadline)

food_site/manufacturing_goals/forms.py
from django import forms
from .models import ManufacturingGoal
import datetime

class GoalsForm(forms.Form):
	name = forms.CharField(label='Goal Name', max_length=500, required=True)
	deadline = forms.DateField(initial=datetime.date.today)

class ManufacturingSchedForm(forms.Form):
	data = forms.CharField(label='Data', required=True)
	overrides = forms.CharField(label='Overrides', required=True)

food_site/manufacturing_goals/views.py
from django.shortcuts import render, redirect
from django.db.models import Q
from sku_manage.models import SKU, Ingredient, ProductLine, ManufacturingLine, IngredientQty, SkuMfgLine
from django_tables2 import RequestConfig, paginators
from .tables import SKUTable, MfgQtyTable, EnableTable, SKUTable2, AutoAddTable, AutoRemoveTable, ProjectionTable
from .models import ManufacturingQty, ManufacturingGoal, ScheduleItem
from home.models import PlantManager
from .forms import GoalsForm, ManufacturingSchedForm
from django.views import generic
from django.forms import inlineformset_factory
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.admin.views.decorators import staff_member_required
import json
from django.core.exceptions import ValidationError
from datetime import datetime, date, time, timedelta
from manufacturing_goals.autoschedule import autoschedule
from . import unitconvert
from sales.models import SalesRecord
from django.utils import timezone
import math

@permission_required('manufacturing_goals.view_manufacturinggoal')
def manufacturing(request):
    if request.method == 'POST':
        form = GoalsForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            deadline = form.cleaned_data['deadline']
            goal_obj = ManufacturingGoal(name=name, user=request.user, deadline=deadline)
            goal_obj.save()
            request.session['goal_id'] = goal_obj.id
            return redirect('manufqty')
        if 'goal' in request.POST:
            goal = ManufacturingGoal.objects.get(pk=request.POST['goal'])
            goal_qty = goal.manufacturingqty_set.all()
            goal_list = list()
            goalcalc_list = list()
            for mq in goal_qty:
                # Details about the Goal itself
                sku = mq.sku
                norm_qty = mq.caseqty
                caseqty = '{:f}'.format(norm_qty)
                mq_info = {"name": sku.name, "sku_number": sku.sku_num, "unit_size": sku.unit_size, "units_per_case": sku.units_per_case, "case_quantity": caseqty}
                goal_list.append(mq_info)
                # Calculation and report
                mq_dict = dict()
                iqtotalslist = list()
                mq_dict["sku"] = str(sku)
                mq_dict["sku_num"] = sku.sku_num
                mq_dict["unit_size"] = sku.unit_size
                mq_dict["units_per_case"] = sku.units_per_case
                formula = sku.formula
                for iq in formula.ingredientqty_set.all():
                    ingtotalunits = (unitconvert.convert(iq.quantity, iq.quantity_units, iq.ingredient.package_size_units) * mq.caseqty * sku.formula_scale)
                    ingtotalpkgs = (ingtotalunits/iq.ingredient.package_size)
                    iqtotalslist.append({iq.ingredient.name: ['{:g}'.format(ingtotalunits)+' '+iq.ingredient.package_size_units, '{:g}'.format(ingtotalpkgs)+' packages']})
                mq_dict["ingredienttotals"] = iqtotalslist
                goalcalc_list.append(mq_dict)
            request.session['goal_name'] = goal.name
            request.session['goal_export_info'] = goal_list
            request.session['goal_calc_list'] = goalcalc_list
            request.session['goal_id'] = goal.id
            return redirect('manufdetails')

    form = GoalsForm()
    queryset = ManufacturingGoal.objects.all()
    table = EnableTable(queryset)
    RequestConfig(request, paginate=False).configure(table)
    context = {
        'enable_table': table,
        'form': form,
    }
    return render(request, "manufacturing_goals/manufacturing.html", context)

@permission_required('manufacturing_goals.add_manufacturinggoal')
def manufqty(request):
    context = {
        'paginated': True,
        'keyword': '',
        'mfg_lines': ManufacturingLine.objects.all(),
        'all_ingredients': Ingredient.objects.all(),
        'selected_ingredient': None,
        'all_product_lines': ProductLine.objects.all(),
        'selected_product_line': None,
        'errormsg': request.session.get('errormsg'),
        'startday': '',
        'startdayrange': [str(i) for i in range(1, 32)],
        'startmonth': '',
        'endday': '',
        'enddayrange': [str(i) for i in range(1, 32)],
        'endmonth': '',
    }   
    paginate = {
        'paginator_class': paginators.LazyPaginator,
        'per_page': 25,
    }
    goal = ManufacturingGoal.objects.get(pk=request.session['goal_id'])
    mfgqtys = ManufacturingQty.objects.filter(goal=goal)
    sku_list = mfgqtys.values_list('sku__id', flat=True)
    queryset = SKU.objects.exclude(id__in=sku_list)
    if request.method == 'GET':
        if 'keyword' in request.GET:
            keyword = request.GET['keyword']
            queryset = queryset.filter(Q(name__icontains=keyword) | 
                Q(sku_num__iexact=keyword) |
                Q(case_upc__iexact=keyword) |
                Q(unit_upc__iexact=keyword) |
                Q(unit_size__icontains=keyword) | 
                Q(units_per_case__iexact=keyword) | 
                Q(mfg_rate__iexact=keyword) |
                Q(mfg_setup_cost__iexact=keyword) |
                Q(mfg_run_cost__iexact=keyword) |
                Q(comment__icontains=keyword))
            context['keyword'] = keyword

        if 'ingredientfilter' in request.GET:
            ingr_num = request.GET['ingredientfilter']
            if ingr_num != 'all':
                queryset = queryset.filter(formula__ingredientqty__ingredient__number=ingr_num)
                context['selected_ingredient'] = int(ingr_num)

        if 'productlinefilter' in request.GET:
            pl_name = request.GET['productlinefilter']
            if pl_name != 'all':
                queryset = queryset.filter(product_line__name=pl_name)
                context['selected_product_line'] = pl_name

        if 'remove_pagination' in request.GET:
            paginate = False
            context['paginated'] = False

    if request.method == 'POST':
        request.session['projection_autofill_value'] = None
        request.session['projection_autofill_pk'] = None
        if 'done' in request.POST:
            return redirect('manufacturing')
        if 'delete' in request.POST:
            goal.delete()
            return redirect('manufacturing')

    input_table = SKUTable(queryset)
    mfgqty_table = MfgQtyTable(mfgqtys)
    context['input_table'] = input_table
    context['selected_table'] = mfgqty_table
    sday = request.session.get('start_day', '')
    smonth = request.session.get('start_month', '')
    eday = request.session.get('end_day', '')
    emonth = request.session.get('end_month', '')
    context['startday'] = sday
    context['startmonth'] = smonth
    context['endday'] = eday
    context['endmonth'] = emonth
    if smonth in ('9', '4', '6', '11'):
        context['startdayrange'] = [str(i) for i in range(1, 31)]
    elif smonth == '2':
        context['startdayrange'] = [str(i) for i in range(1, 29)]
    if emonth in ('9', '4', '6', '11'):
        context['enddayrange'] = [str(i) for i in range(1, 31)]
    elif emonth == '2':
        context['enddayrange'] = [str(i) for i in range(1, 29)]
    RequestConfig(request, paginate=paginate).configure(input_table)
    RequestConfig(request, paginate=paginate).configure(mfgqty_table)
    return render(request, 'manufacturing_goals/data.html', context)

@permission_required('manufacturing_goals.add_manufacturinggoal')
def goal_add(request, pk):
    try:
        goal = ManufacturingGoal.objects.get(pk=request.session['goal_id'])
        sku = SKU.objects.get(pk=pk)
        caseqty = request.POST['case_qty']
        ManufacturingQty(sku=sku, goal=goal, caseqty=caseqty).save()
        goal.save()
        request.session['errormsg'] = ''
    except (ValueError, ValidationError):
        request.session['errormsg'] = 'Include Case Quantity'
    return redirect('manufqty')

@permission_required('manufacturing_goals.add_manufacturinggoal')
def goal_remove(request, pk):
    goal = ManufacturingGoal.objects.get(pk=request.session['goal_id'])
    ManufacturingQty.objects.get(pk=pk).delete()
    goal.save()
    request.session['errormsg'] = ''
    return redirect('manufqty')

@permission_required('manufacturing_goals.view_manufacturinggoal')
def manufcalc(request):
    form = GoalsChoiceForm(user=request.user)
    if request.method == "POST":
        form = GoalsChoiceForm(request.POST, user=request.user)
        if form.is_valid():
            goalcalc_list = list()
            goal = form.cleaned_data['goal']
            goal_qty = goal.manufacturingqty_set.all()
            for mq in goal_qty:
                mq_dict = dict()
                iq_totalslist = list()
                sku = mq.sku
                mq_dict["sku"] = str(sku)
                mq_dict["sku_num"] = sku.sku_num
                mq_dict["unit_size"] = sku.unit_size
                mq_dict["units_per_case"] = sku.units_per_case
                ingredientqtys = sku.ingredientqty_set.all()
                for iq in ingredientqtys:
                    ingredient = iq.ingredient
                    i_qty = iq.quantity
                    ingtotal = (i_qty * mq.caseqty).normalize()
                    iq_totalslist.append({ingredient.name: '{:f}'.format(ingtotal)})
                mq_dict["ingredienttotals"] = iq_totalslist
                goalcalc_list.append(mq_dict)
            request.session['goal_calc_name'] = goal.name
            request.session['goal_calc_list'] = goalcalc_list
            return redirect('calcresults')
    return render(request, 'manufacturing_goals/manufcalc.html', {'form': form})

@permission_required('manufacturing_goals.view_manufacturinggoal')
def calcresults(request):
    goal_name = request.session['goal_calc_name']
    goal_list = request.session['goal_calc_list']

food_site/manufacturing_goals/templates/manufacturing_goals/addcolumn.html
<div class="form-inline thin-wide">
	<form class="thin" action="{% url 'mfg_goal_add' record.pk %}" method="post">
		{% csrf_token %}
		<input class="narrow" type="number" name="case_qty" {% if record.pk == request.session.projection_autofill_pk %} value="{{ request.session.projection_autofill_value  }}" {% endif %} placeholder="Case Quantity">
		<button type="submit"><i class="fa fa-plus"></i></button>
	</form>
	<form class="thin-wide" action="{% url 'projection' record.pk %}" method="get">
	        <button type="submit">Project Sales</button>
	</form>
</div>

food_site/manufacturing_goals/templates/manufacturing_goals/autoscheduleselect.html
{% extends "base.html" %}
{% block content %}
	<h1>HypoScheduler<sup>&#174;</sup></h1>
	<div class="inline">
		<form class="form-inline" method="get">
	        <p>Start:</p>
	        <input class="narrow" name="startdate" type="date" value="{{ start_date }}" onchange='this.form.submit()'>
	        <input class="narrow" name="starttime" type="time" value="{{ start_time }}" onchange='this.form.submit()'>
	        <p>End:</p>
	        <input class="narrow" name="enddate" type="date" value = "{{ end_date }}" onchange='this.form.submit()'>
	        <input class="narrow" name="endtime" type="time" value = "{{ end_time }}" onchange='this.form.submit()'>
	    </form>
		<a class="btn" href="{% url 'auto_schedule' %}"><i class="fa fa-arrow-right"></i></a>	
		<a class="btn" href="{% url 'timeline' %}"><i class="fa fa-close"></i></a>
	</div>
	<br>
	<form class="form-inline" method="post">
		{% csrf_token %}
		<button type="submit" name="add_all">Add All</button>
		<button type="submit" name="remove_all">Remove All</button>
	</form>
	<div class="row">
		<div class="column">
			<div class="table" style="overflow-x:auto;">
				{% load render_table from django_tables2 %}
				{% load bootstrap3 %}
				{% render_table input_table %}
			</div>
		</div>
		<div class="column">
			<div class="table" style="overflow-x:auto;">
				{% render_table selected_table %}
			</div>
		</div>
	</div>
{% endblock content %}

food_site/manufacturing_goals/templates/manufacturing_goals/calcresults.html
<!DOCTYPE html>

<head>
                {% load static %}
                <meta charset="utf-8">
                <title>HypoMeals</title>
                <link rel="stylesheet" type="text/css" href="{% static "manufacturing_goals/data.css" %}" />
</head>

<body>
	<div id="dvContainer">
	<h3>Manufacturing Calculator Results</h3>
	<h4>{{ goal_name }}</h4>
	{% for g in goal_list %}
	<strong>{{ g.sku }}</strong>
	<table class="ingredient_table" style="margin-bottom:10px">
		<!--<tr hidden><th>sku</th><th>ingredient</th><th>quantity</th></tr>-->
		{% for i in g.ingredienttotals %}
			<tr>
				{% for k, v in i.items %}
					<td hidden>{{ g.sku }}</td>
					<td>{{ k }}</td>
					<td>{{ v }}</td>
				{% endfor %}
			</tr>
		{% endfor %}
	</table>
	{% endfor %}
	</div>
	<a href="#" id="xx">Export to CSV</a><br>
	<input type="button" value="Print Goal Calculation" id="btnPrint" /><br>
	<a href='/manufacturing/'>Back to Manufacturing</a>
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script>
	function exportTableToCSV($table, filename) {
		var $rows = $table.find('tr:has(td),tr:has(th)'),
			tmpColDelim = String.fromCharCode(11),
			tmpRowDelim = String.fromCharCode(0),
			colDelim = '","',
			rowDelim = '"\r\n"',
			csv = '"sku","ingredient","quantity"\r\n"' + $rows.map(function (i, row) {
				var $row = $(row), $cols = $row.find('td,th');
				return $cols.map(function (j, col) {
					var $col = $(col), text = $col.text();
					return text.replace(/"/g, '""');
				}).get().join(tmpColDelim);
			}).get().join(tmpRowDelim).split(tmpRowDelim).join(rowDelim).split(tmpColDelim).join(colDelim) + '"',
			csvData = 'data:application/csv;charset=utf-8,' + encodeURIComponent(csv);
			console.log(csv);
			if (window.navigator.msSaveBlob){
				window.navigator.msSaveOrOpenBlob(new Blob([csv], {type: "text/plain;charset=utf-8;"}), "csvname.csv");
			}
			else {
				$(this).attr({ 'download': filename, 'href': csvData, 'target': '_blank' });
			}
	}
$("#xx").on('click', function (event) {
	exportTableToCSV.apply(this, [$('.ingredient_table'), '{{ goal_name }}_calculation_export.csv']);
});
</script>
<script type="text/javascript">
	$("body").on("click", '#btnPrint', function(){
		var divContents = $("#dvContainer").html();
		var printWindow = window.open('', '', 'height=400,width=800');
		printWindow.document.write('<html><head><title>{{ goal_name }} Calculation</title></head><body>');
		printWindow.document.write(divContents);
		printWindow.document.write('</body></html>');
		printWindow.document.close();
		printWindow.print();
	});
</script>
</body>

food_site/manufacturing_goals/templates/manufacturing_goals/data.html
{% extends "base.html" %}
{% block content %}
	<h1>Edit Manufacturing Goal:</h1>
	<div class="warnings">
		{% if errormsg %}<p>{{ errormsg }}</p>{% endif %}
	</div>
	<form class="form-inline" method="POST" action="{% url 'dateset' %}">
		{% csrf_token %}
		<p>Sales Projection Start Date:</p>
		<select name="smonth" onchange='this.form.submit()'>
			<option value="">Select Month</option>
			<option value="1" {% if startmonth == '1' %}selected{% endif %}>January</option>
			<option value="2" {% if startmonth == '2' %}selected{% endif %}>February</option>
			<option value="3" {% if startmonth == '3' %}selected{% endif %}>March</option>
			<option value="4" {% if startmonth == '4' %}selected{% endif %}>April</option>
			<option value="5" {% if startmonth == '5' %}selected{% endif %}>May</option>
			<option value="6" {% if startmonth == '6' %}selected{% endif %}>June</option>
			<option value="7" {% if startmonth == '7' %}selected{% endif %}>July</option>
			<option value="8" {% if startmonth == '8' %}selected{% endif %}>August</option>
			<option value="9" {% if startmonth == '9' %}selected{% endif %}>September</option>
			<option value="10" {% if startmonth == '10' %}selected{% endif %}>October</option>
			<option value="11" {% if startmonth == '11' %}selected{% endif %}>November</option>
			<option value="12" {% if startmonth == '12' %}selected{% endif %}>December</option>
		</select>
		<select name="sday" onchange='this.form.submit()'>
			<option value="">Select Day</option>
			{% for num in startdayrange %}
				<option value="{{ num }}" {% if startday == num %}selected{% endif %}>{{ num }}</option>
			{% endfor %}
		</select>
		<p>End Date:</p>
		<select name="emonth" onchange='this.form.submit()'>
			<option value="">Select Month</option>
			<option value="1" {% if endmonth == '1' %}selected{% endif %}>January</option>
			<option value="2" {% if endmonth == '2' %}selected{% endif %}>February</option>
			<option value="3" {% if endmonth == '3' %}selected{% endif %}>March</option>
			<option value="4" {% if endmonth == '4' %}selected{% endif %}>April</option>
			<option value="5" {% if endmonth == '5' %}selected{% endif %}>May</option>
			<option value="6" {% if endmonth == '6' %}selected{% endif %}>June</option>
			<option value="7" {% if endmonth == '7' %}selected{% endif %}>July</option>
			<option value="8" {% if endmonth == '8' %}selected{% endif %}>August</option>
			<option value="9" {% if endmonth == '9' %}selected{% endif %}>September</option>
			<option value="10" {% if endmonth == '10' %}selected{% endif %}>October</option>
			<option value="11" {% if endmonth == '11' %}selected{% endif %}>November</option>
			<option value="12" {% if endmonth == '12' %}selected{% endif %}>December</option>
		</select>
		<select name="eday" onchange='this.form.submit()'>
			<option value="">Select Day</option>
			{% for num in enddayrange %}
				<option value="{{ num }}" {% if endday == num %}selected{% endif %}>{{ num }}</option>
			{% endfor %}
		</select>
	</form>
	<br>	
	{% include "data/filters.html" %}
	<br>	
	<form class="inline" method="post">
		{% csrf_token %}
		<button type="submit" name="done" {% if not selected_table.rows %} disabled {% endif %}><i class="fa fa-save"></i></button>	
		<button type="submit" name="delete"><i class="fa fa-trash"></i></button>
	</form>
	<br>
	<div class="row">
		<div class="column">
			<div class="table" style="overflow-x:auto;">
				{% load render_table from django_tables2 %}
				{% load bootstrap3 %}
				{% render_table input_table %}
			</div>
			<form class="form-inline" method="get">
				{% if queryset.all|length > 25 %}
					{% if paginated %}
						<button type="submit" name="remove_pagination">View All Records</button>
					{% else %}
						<button type="submit" name="add_pagination">Paged View</button>
					{% endif %}
				{% endif %}
			</form>
		</div>
		<div class="column">
			<div class="table" style="overflow-x:auto;">
				{% render_table selected_table %}
			</div>
		</div>
	</div>
{% endblock content %}

food_site/manufacturing_goals/templates/manufacturing_goals/enable_menu.html
{% extends "base.html" %}
{% block content %}
	<h1>Enable and Disable Manufacturing Goals:</h1>
	<div class="table" style="overflow-x:auto;">
		{% load render_table from django_tables2 %}
		{% load bootstrap3 %}
		{% render_table table %}
	</div>
{% endblock content %}

food_site/manufacturing_goals/templates/manufacturing_goals/goalnamecolumn.html
<div class="inline">
	<form method="post" action="{% url 'manufacturing' %}">
		{% csrf_token %}
		<button class="btn" type="submit" name="goal" value="{{ record.pk }}"><i class="fa fa-eye"></i></button>
	</form>
	&nbsp {{ record.name }}
</div>

food_site/manufacturing_goals/templates/manufacturing_goals/manufacturing.html
{% extends "base.html" %}
{% block content %}
	<h1>Manufacturing Goals</h1>
	{% if perms.manufacturing_goals.add_manufacturinggoal %}
		<h2>Create a New Manufacturing Goal</h2>
		<form class="form-inline" method="POST">
			{% csrf_token %}
			<p>Name:</p>
			<input value="{{ name }}" type="text" name="name" maxlength="500" id="name" required="required" placeholder="Goal Name">
			<p>Deadline:</p>
			<input value="{{ deadline }}" type="date" name="deadline" required="required">
			<button type="submit" id="submit" name="submit">Create New Goal</button>
		</form>
		<h2>Existing Manufacturing Goals</h2> 
	{% endif %}
	<div class="table" style="overflow-x:auto;">
		{% load render_table from django_tables2 %}
		{% load bootstrap3 %}
		{% render_table enable_table %}
	</div>
	<br>
	{% if perms.manufacturing_goals.view_scheduleitem %}
	<div class="menu-buttons" style="text-align: left">
		<a class="btn" href="{% url 'timeline_viewer' %}">Manufacturing Timeline</a>
	</div>
	{% endif %}
{% endblock content %}

food_site/manufacturing_goals/templates/manufacturing_goals/remcolumn.html
<form class="form-inline thin" action="{% url 'mfg_goal_remove' record.pk %}" method="post">
	{% csrf_token %}
	<button type="submit"><i class="fa fa-close"></i></button>
</form>