food_site/food_site/urls.py
from sku_manage.admin import admin_site
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin_site.urls),
    path('', include('home.urls')),
    path('importer/', include('importer.urls')),
    path('reporting/', include('dep_report.urls')),
    path('reporting/', include('sales.urls')),
    path('search/', include('sku_manage.urls')),
    path('manufacturing/', include('manufacturing_goals.urls')),
    path('mfglinemap/', include('mfg_map.urls')),
]

food_site/home/urls.py
# home/urls.py
from django.conf.urls import url
from home import views
from django.urls import path


urlpatterns = [
    path('', views.index, name='index'),
    path('authin/', views.authin, name='authin'),
    path('authout/', views.authout, name='authout'),
    path('invalidlogin/', views.invalidlogin, name='invalidlogin'),
    path('help/', views.help, name='help'),
    path('aboutus/', views.aboutus, name='aboutus'),
    path('netlog/', views.netlog, name='netlog'),
    path('netret/', views.netret, name='netret'),
    path('authmid/', views.authmid, name='authmid'),
    path('user/', views.selectuser, name='selectuser'),
    path('user/<int:pk>/', views.edituser, name='edituser'),
    path('assistant/', views.assistant, name='assistant'),
    path('cya/', views.cya, name='cya'),
    path('cyaend/', views.cya_end, name='cyaend'),
    path('privacy-policy/', views.privacy, name='privacy-policy'),
]

food_site/sku_manage/models.py
import re

from django.db import models
from django.core.exceptions import ValidationError

weights = ('Ounce', 'oz.', 'Pound', 'lb.', 'Ton', 'ton.', 'Gram', 'g.', 'Kilogram', 'kg.')
volumes = ('Fluid Ounce', 'fl.oz.', 'Pint', 'pt.', 'Quart', 'qt.', 'Gallon', 'gal.', 'Milliliter', 'mL', 'Liter', 'L')
counts = ('Count', 'count',)

def validate_upc(value):
    if len(value) != 12:
        raise ValidationError('UPC must be 12 digits long')
    pattern = re.compile('[0-9]{12}')
    if pattern.match(value) is None:
        raise ValidationError('UPC must only contain numbers')
    if 1 < int(value[0]) < 6:
        raise ValidationError('UPC first digit is not valid')
    sum_val = 0
    for i in range(0, 6):
        sum_val += int(value[i * 2])
    sum_val = sum_val * 3
    for i in range(0, 6):
        sum_val += int(value[i * 2 + 1])
    if sum_val % 10 != 0:
        raise ValidationError('UPC check digit is not valid')


def validate_gt_zero(value):
    if value <= 0:
        raise ValidationError('Must be greater than zero')


def gen_ingr_num():
    ingredients = Ingredient.objects.order_by('number')
    if len(ingredients) > 0 and ingredients[len(ingredients) - 1].number > len(ingredients) - 1:
        for i in range(0, len(ingredients)):
            if (ingredients[i].number > i):
                return i
    return len(ingredients)


def gen_sku_num():
    skus = SKU.objects.order_by('sku_num')
    if len(skus) > 0 and skus[len(skus) - 1].sku_num > len(skus) - 1:
        for i in range(0, len(skus)):
            if (skus[i].sku_num > i):
                return i
    return len(skus)


def gen_fla_num():
    formulas = Formula.objects.order_by('number')
    if len(formulas) > 0 and formulas[len(formulas) - 1].number > len(formulas) - 1:
        for i in range(0, len(formulas)):
            if (formulas[i].number > i):
                return i
    return len(formulas)


class Ingredient(models.Model):
    name = models.CharField(max_length=256, unique=True, verbose_name='Ingredient Name')
    number = models.PositiveIntegerField(unique=True, default=gen_ingr_num, verbose_name='Ingredient#')
    vendor_info = models.TextField(blank=True, verbose_name='Vendor Information')
    package_size = models.FloatField(validators=[validate_gt_zero])
    package_size_units = models.CharField(max_length=16,
                                          choices=[('Ounce', 'oz.'), ('Pound', 'lb.'), ('Ton', 'ton.'), ('Gram', 'g.'),
                                                   ('Kilogram', 'kg.'), ('Fluid Ounce', 'fl.oz.'), ('Pint', 'pt.'),
                                                   ('Quart', 'qt.'), ('Gallon', 'gal.'), ('Milliliter', 'mL'),
                                                   ('Liter', 'L'), ('Count', 'count')])
    cost = models.DecimalField(max_digits=12, decimal_places=2, validators=[validate_gt_zero])
    comment = models.TextField(blank=True)

    class Meta:
        permissions = (('report_ingredient', 'Can view ingredient dependency report'),)

    def __str__(self):
        return self.name

    def get_serializable_string_array(self):
        return [str(self.number), self.name, self.vendor_info, str(self.package_size), self.package_size_units,
                str(self.cost), self.comment]


class ProductLine(models.Model):
    name = models.CharField(max_length=256, unique=True)

    def __str__(self):
        return self.name


class Formula(models.Model):
    name = models.CharField(max_length=32)
    number = models.IntegerField(unique=True, default=gen_fla_num, verbose_name='Formula#')
    comment = models.TextField(blank=True)

    def __str__(self):
        return self.name

    def get_serializable_string_array(self):
        return [str(self.number), self.name, str(self.comment)]


class SKU(models.Model):
    name = models.CharField(max_length=32)
    sku_num = models.IntegerField(unique=True, default=gen_sku_num, verbose_name='SKU#')
    case_upc = models.CharField(max_length=12, unique=True, validators=[validate_upc], verbose_name='Case UPC')
    unit_upc = models.CharField(max_length=12, validators=[validate_upc], verbose_name='Unit UPC')
    unit_size = models.CharField(max_length=256)
    units_per_case = models.PositiveIntegerField(validators=[validate_gt_zero])
    product_line = models.ForeignKey(ProductLine, on_delete=models.PROTECT)
    formula = models.ForeignKey(Formula, on_delete=models.PROTECT)
    formula_scale = models.FloatField(default=1.0, validators=[validate_gt_zero], verbose_name='Formula Scale Factor')
    mfg_rate = models.FloatField(validators=[validate_gt_zero], verbose_name='Manufacturing Rate')
    mfg_setup_cost = models.DecimalField(max_digits=12, decimal_places=2, validators=[validate_gt_zero], verbose_name='Manufacturing Setup Cost')
    mfg_run_cost = models.DecimalField(max_digits=12, decimal_places=2, validators=[validate_gt_zero], verbose_name='Manufacturing Run Cost per Case')
    comment = models.TextField(blank=True)

    def __str__(self):
        return "{name}: {unit_size} * {units_per_case} (SKU#{sku_num})".format(name=self.name, unit_size=self.unit_size, units_per_case=self.units_per_case, sku_num=self.sku_num)

    def get_serializable_string_array(self):
        return [str(self.sku_num), self.name, self.case_upc, self.unit_upc, self.unit_size, str(self.units_per_case),
                self.product_line.name, str(self.formula.number), str(self.formula_scale), str(self.mfg_rate),
                str(self.mfg_setup_cost), str(self.mfg_run_cost), self.comment]

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        from sales import tasks
        tasks.scrape_sku(self.sku_num)

class ManufacturingLine(models.Model):
    name = models.CharField(max_length=32)
    shortname = models.CharField(max_length=5, unique=True)
    comment = models.TextField(blank=True)

    class Meta:
        permissions = (('report_manufacturingline', 'Can view manufacturing schedule reports'),)

    def __str__(self):
        return "{name} ({shortname})".format(name=self.name, shortname=self.shortname)


class IngredientQty(models.Model):
    formula = models.ForeignKey(Formula, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.PROTECT)
    quantity = models.FloatField(validators=[validate_gt_zero])
    quantity_units = models.CharField(max_length=16,
                                      choices=[('Ounce', 'oz.'), ('Pound', 'lb.'), ('Ton', 'ton.'), ('Gram', 'g.'),
                                                 ('Kilogram', 'kg.'), ('Fluid Ounce', 'fl.oz.'), ('Pint', 'pt.'),
                                                 ('Quart', 'qt.'), ('Gallon', 'gal.'), ('Milliliter', 'mL'),
                                                 ('Liter', 'L'), ('Count', 'count')])

    class Meta:
        unique_together = ("formula", "ingredient")

    def clean(self):
        if self.quantity_units in weights and self.ingredient.package_size_units not in weights:
            raise ValidationError("Quantity measured in weight but ingredient package size is not")
        if self.quantity_units in volumes and self.ingredient.package_size_units not in volumes:
            raise ValidationError("Quantity measured in volume but ingredient package size is not")
        if self.quantity_units in counts and self.ingredient.package_size_units not in counts:
            raise ValidationError("Quantity measured in raw count but ingredient package size is not")

    def get_serializable_string_array(self):
        return [str(self.formula.number), str(self.ingredient.number), str(self.quantity), str(self.quantity_units)]


class SkuMfgLine(models.Model):
    sku = models.ForeignKey(SKU, on_delete=models.CASCADE)
    mfg_line = models.ForeignKey(ManufacturingLine, on_delete=models.PROTECT)

    class Meta:
        unique_together = ("sku", "mfg_line")

food_site/templates/base.html
<!DOCTYPE html>
<html>
    {% load staticfiles %}
    {% load static %}
    <head>
        <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}"/>
        <meta charset="utf-8">
            <title>HypoMeals</title>
            <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
            <link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}" />
            {% if request.session.cya %}
                <link rel="stylesheet" type="text/css" href="{% static "css/cya.css" %}" />
            {% endif %}
            {% block styling %}{% endblock styling %}
    </head>
    <body>
        {% if user.is_authenticated %}
            {% include "header.html" %} 
        {% endif %}
        {% block content %}
        {% endblock content %}
        {% if request.session.cya and not request.path == '/' %}
        <div class="ret">
            <br>
            {% if ingredient.name == 'Hylian Shroom' %}
                <a href="{% url 'cyaend' %}"><img src="https://www.zelda.com/assets/img/home/button_decoration_left.png">Restore Peace to Hyrule<img src="https://www.zelda.com/assets/img/home/button_decoration_right.png"></a>
                <audio autoplay>
                    <source src="{% static 'audio/zelda2.wav' %}" type="audio/wav">
                </audio>
            {% elif ingredient.name == 'Silent Princess' %}
                <a href="{% url 'cyaend' %}"><img src="https://www.zelda.com/assets/img/home/button_decoration_left.png">Defeat Ganon<img src="https://www.zelda.com/assets/img/home/button_decoration_right.png"></a>
                <audio autoplay>
                    <source src="{% static 'audio/zelda2.wav' %}" type="audio/wav">
                </audio>
            {% elif ingredient.name == 'Korok Seed' %}
                <a href="{% url 'cyaend' %}"><img src="https://www.zelda.com/assets/img/home/button_decoration_left.png">You found Hestu!<img src="https://www.zelda.com/assets/img/home/button_decoration_right.png"></a>
                <audio autoplay>
                    <source src="{% static 'audio/hestu.wav' %}" type="audio/wav">
                </audio>
            {% else %}
                <a href="{{ request.path }}../"><img src="https://www.zelda.com/assets/img/home/button_decoration_left.png">Return<img src="https://www.zelda.com/assets/img/home/button_decoration_right.png"></a>
            {% endif %}
            <br>
        </div>
        {% endif %}
    <br>
    </body>
</html>

food_site/templates/header.html
<div class="topnav">
	<a {% if request.path == '/' %} class="active" {% endif %} href="/">Home</a>
	<div class="dropdown">
		<a {% if request.path|slice:":7" == '/search' %} class="active" {% endif %} href="/search/">Data</a>
		<div class="dropdown-content">
			<a href="/search/ingredient/">Ingredients</a>
			<a href="/search/productline/">Product Lines</a>
			<a href="/search/sku/">SKUs</a>
			<a href="/search/formula/">Formulas</a>
			<a href="/search/manufacturingline/">Manufacturing Lines</a>
		</div>
	</div>
	{% if perms.sku_manage.report_ingredient or perms.sku_manage.report_manufacturingline or perms.sales.report_salesrecord %}
		<div class="dropdown">
			<a {% if request.path|slice:":10" == '/reporting' %} class="active" {% endif %} href="/reporting/">Reporting</a>
			<div class="dropdown-content">
				{% if perms.sku_manage.report_ingredient %}
					<a href="/reporting/ingredient/">Ingredient Dependency</a>
				{% endif %}
				{% if perms.sku_manage.report_manufacturingline %}
					<a href="/reporting/manufacturing/">Manufacturing Schedule</a>
				{% endif %}
				{% if perms.sales.report_salesrecord %}
					<a href="/reporting/sales/">Sales</a>
				{% endif %}
			</div>
		</div>
	{% endif %}
	{% if perms.manufacturing_goals.view_manufacturinggoal %}
		<div class="dropdown">
			<a {% if request.path|slice:":14" == '/manufacturing' %} class="active" {% endif %} href="/manufacturing/">Manufacturing</a>
				{% if perms.manufacturing_goals.view_scheduleitem %}
				<div class="dropdown-content">
					<a href="/manufacturing/">Manufacturing Goals</a>
					<a href="/manufacturing/timeline/">Manufacturing Timeline</a>
				</div>			
			{% endif %}
		</div>
	{% endif %}
	{% if perms.auth.add_user or perms.auth.change_user or perms.sku_manage.add_sku or perms.sku_manage.change_skumfgline %}
		<div class="dropdown">
			<a {% if request.path|slice:":6" == '/admin' or request.path|slice:":9" == '/importer' or request.path|slice:":11" == '/mfglinemap' or request.path|slice:":5" == '/user' %} class="active" {% endif %}>Administration</a>
			<div class="dropdown-content">
				{% if perms.auth.add_user %}
					<a href="/admin/">Site Administration</a>
				{% endif %}
				{% if perms.auth.change_user %}
					<a href="/user/">User Roles</a>
				{% endif %}
				{% if perms.sku_manage.add_sku %}
					<a href="/importer/">CSV Data Import</a>
				{% endif %}
				{% if perms.sku_manage.change_skumfgline %}
					<a href="/mfglinemap/">Manufacturing Line Mapping</a>
				{% endif %}
			</div>
		</div>
	{% endif %}
	<a class="right-justify" href="/authout/">Log Out</a>
</div>